from enum import Enum


class ExtraComputation(Enum):
    EXTRA_COMPUTATION_UNSPECIFIED = "EXTRA_COMPUTATION_UNSPECIFIED"
    TOLLS = "TOLLS"
    FUEL_CONSUMPTION = "FUEL_CONSUMPTION"
    TRAFFIC_ON_POLYLINE = "TRAFFIC_ON_POLYLINE"
    HTML_FORMATTED_NAVIGATION_INSTRUCTIONS = "HTML_FORMATTED_NAVIGATION_INSTRUCTIONS"
    FLYOVER_INFO_ON_POLYLINE = "FLYOVER_INFO_ON_POLYLINE"
    NARROW_ROAD_INFO_ON_POLYLINE = "NARROW_ROAD_INFO_ON_POLYLINE"


class FallbackReason(Enum):
    FALLBACK_REASON_UNSPECIFIED = "FALLBACK_REASON_UNSPECIFIED"
    SERVER_ERROR = "SERVER_ERROR"
    LATENCY_EXCEEDED = "LATENCY_EXCEEDED"


class FallbackRoutingMode(Enum):
    FALLBACK_ROUTING_MODE_UNSPECIFIED = "FALLBACK_ROUTING_MODE_UNSPECIFIED"
    FALLBACK_TRAFFIC_UNAWARE = "FALLBACK_TRAFFIC_UNAWARE"
    FALLBACK_TRAFFIC_AWARE = "FALLBACK_TRAFFIC_AWARE"


class RoadFeatureState(Enum):
    ROAD_FEATURE_STATE_UNSPECIFIED = "ROAD_FEATURE_STATE_UNSPECIFIED"
    EXISTS = "EXISTS"
    DOES_NOT_EXIST = "DOES_NOT_EXIST"


class RouteLabels(Enum):
    ROUTE_LABELS_UNSPECIFIED = "ROUTE_LABELS_UNSPECIFIED"
    DEFAULT_ROUTE = "DEFAULT_ROUTE"
    DEFAULT_ROUTE_ALTERNATIVE = "DEFAULT_ROUTE_ALTERNATIVE"
    FUEL_EFFICIENT = "FUEL_EFFICIENT"
    SHORTEST_DISTANCE = "SHORTEST_DISTANCE"


class RouteTravelMode(Enum):
    TRAVEL_MODE_UNSPECIFIED = "TRAVEL_MODE_UNSPECIFIED"
    DRIVE = "DRIVE"
    BICYCLE = "BICYCLE"
    WALK = "WALK"
    TWO_WHEELER = "TWO_WHEELER"
    TRANSIT = "TRANSIT"


class RoutingPreference(Enum):
    ROUTING_PREFERENCE_UNSPECIFIED = "ROUTING_PREFERENCE_UNSPECIFIED"
    TRAFFIC_UNAWARE = "TRAFFIC_UNAWARE"
    TRAFFIC_AWARE = "TRAFFIC_AWARE"
    TRAFFIC_AWARE_OPTIMAL = "TRAFFIC_AWARE_OPTIMAL"


class Speed(Enum):
    SPEED_UNSPECIFIED = "SPEED_UNSPECIFIED"
    NORMAL = "NORMAL"
    SLOW = "SLOW"
    TRAFFIC_JAM = "TRAFFIC_JAM"


class TollPass(Enum):
    pass


class TrafficModel(Enum):
    TRAFFIC_MODEL_UNSPECIFIED = "TRAFFIC_MODEL_UNSPECIFIED"
    BEST_GUESS = "BEST_GUESS"
    PESSIMISTIC = "PESSIMISTIC"
    OPTIMISTIC = "OPTIMISTIC"


class TransitRoutingPreference(Enum):
    TRANSIT_ROUTING_PREFERENCE_UNSPECIFIED = "TRANSIT_ROUTING_PREFERENCE_UNSPECIFIED"
    LESS_WALKING = "LESS_WALKING"
    FEWER_TRANSFERS = "FEWER_TRANSFERS"


class TransitTravelMode(Enum):
    TRANSIT_TRAVEL_MODE_UNSPECIFIED = "TRANSIT_TRAVEL_MODE_UNSPECIFIED"
    BUS = "BUS"
    SUBWAY = "SUBWAY"
    TRAIN = "TRAIN"
    TRAM = "TRAM"
    RAIL = "RAIL"


class Units(Enum):
    UNITS_UNSPECIFIED = "UNITS_UNSPECIFIED"
    METRIC = "METRIC"
    IMPERIAL = "IMPERIAL"


class VehicleEmissionType(Enum):
    VEHICLE_EMISSION_TYPE_UNSPECIFIED = "VEHICLE_EMISSION_TYPE_UNSPECIFIED"
    GASOLINE = "GASOLINE"
    ELECTRIC = "ELECTRIC"
    HYBRID = "HYBRID"
    DIESEL = "DIESEL"
